---
# yaml-language-server: $schema=https://schema.blue-build.org/module-list-v1.json

modules:
 - type: files
   files:
     - source: base-files
       destination: /

     - source: niri-settings
       destination: /

 - type: script
   snippets:
     - |
       rm -f /usr/share/applications/btop.desktop
       rm -f /usr/share/applications/kbd-layout-viewer5.desktop
       rm -f /usr/share/applications/nvim.desktop
       rm -f /usr/share/applications/nwg-look.desktop
       systemctl enable papirus-accent.path