name: zbuilder (scheduled)
on:
  schedule:
    - cron: "23 09 * * *"
    - cron: "47 15 * * *"
    - cron: "33 22 * * *"
    - cron: "17 3 * * *"

  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true
jobs:
  keepalive:
    name: Keepalive
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Keepalive
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          date -u +"%Y-%m-%d %H:%M:%S" > .keepalive
          git add .keepalive
          git diff --staged --quiet || git commit -m "(Bot) KeepAlive $(date -u +%Y-%m-%d)"
          git push || true

  bluebuild:
    name: zbuild (scheduled)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        recipe:
          - zynori-mesa.yml
          - zynori-nvidia.yml

    steps:
      - name: Build Zodium Image
        uses: blue-build/github-action@v1.11
        with:
          recipe: ${{ matrix.recipe }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
          maximize_build_space: true
          build_chunked_oci: true
          verify_install: true