name: zbuilder (automatic)
on:
  push:
    paths-ignore:
      - "**.md"
      - ".keepalive"
      - ".gitignore"
      - "LICENSE"

  pull_request:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true
jobs:
  bluebuild:
    name: Building-Image (${{ matrix.recipe }})
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        recipe:
          - zynori-mesa.yml
          - zynori-nvidia.yml

    steps:
      - name: BlueBuild-Image Builder
        uses: blue-build/github-action@v1.11
        with:
          recipe: ${{ matrix.recipe }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
          maximize_build_space: true
          build_chunked_oci: true
          verify_install: true